import type {EnhancedMenu} from '~/lib/utils';

export const footerDummy: EnhancedMenu = {
  id: 'footer',
  items: [
    {
      id: 'footer-item-1',
      title: 'Item 1',
      tags: ['tag1', 'tag2'],
      to: '/',
      type: 'ARTICLE',
      target: '_blank',
      items: [
        {
          id: 'footer-item-1-1',
          title: 'Item 1.1',
          tags: ['tag5', 'tag6'],
          to: '/',
          type: 'ARTICLE',
          target: '_blank',
        },
        {
          id: 'footer-item-1-2',
          title: 'Item 1.2',
          tags: ['tag5', 'tag6'],
          to: '/',
          type: 'ARTICLE',
          target: '_blank',
        },
      ],
    },
    {
      id: 'footer-item-2',
      title: 'Item 2',
      tags: ['tag3', 'tag4'],
      to: '/',
      type: 'ARTICLE',
      target: '_blank',
      items: [
        {
          id: 'footer-item-2-1',
          title: 'Item 2.1',
          tags: ['tag5', 'tag6'],
          to: '/',
          type: 'ARTICLE',
          target: '_blank',
        },
        {
          id: 'footer-item-2-2',
          title: 'Item 2.2',
          tags: ['tag5', 'tag6'],
          to: '/',
          type: 'ARTICLE',
          target: '_blank',
        },
        {
          id: 'footer-item-2-3',
          title: 'Item 2.3',
          tags: ['tag5', 'tag6'],
          to: '/',
          type: 'ARTICLE',
          target: '_blank',
        },
      ],
    },
    {
      id: 'footer-item-3',
      title: 'Item 3',
      tags: ['tag5', 'tag6'],
      to: '/',
      type: 'ARTICLE',
      target: '_blank',
      items: [
        {
          id: 'footer-item-3-1',
          title: 'Item 3.1',
          tags: ['tag7', 'tag8'],
          to: '/',
          type: 'ARTICLE',
          target: '_blank',
        },
        {
          id: 'footer-item-3-2',
          title: 'Item 3.2',
          tags: ['tag9', 'tag10'],
          to: '/',
          type: 'ARTICLE',
          target: '_blank',
        },
        {
          id: 'footer-item-3-3',
          title: 'Item 3.3',
          tags: ['tag11', 'tag12'],
          to: '/',
          type: 'ARTICLE',
          target: '_blank',
        },
      ],
    },
    {
      id: 'footer-item-4',
      title: 'Item 4',
      tags: ['tag5', 'tag6'],
      to: '/',
      type: 'ARTICLE',
      target: '_blank',
      items: [
        {
          id: 'footer-item-4-1',
          title: 'Item 4.1',
          tags: ['tag13', 'tag14'],
          to: '/',
          type: 'ARTICLE',
          target: '_blank',
        },
        {
          id: 'footer-item-4-2',
          title: 'Item 4.2',
          tags: ['tag15', 'tag16'],
          to: '/',
          type: 'ARTICLE',
          target: '_blank',
        },
        {
          id: 'footer-item-4-3',
          title: 'Item 4.3',
          tags: ['tag17', 'tag18'],
          to: '/',
          type: 'ARTICLE',
          target: '_blank',
        },
        {
          id: 'footer-item-4-4',
          title: 'Item 4.4',
          tags: ['tag19', 'tag20'],
          to: '/',
          type: 'ARTICLE',
          target: '_blank',
        },
        {
          id: 'footer-item-4-5',
          title: 'Item 4.5',
          tags: ['tag21', 'tag22'],
          to: '/',
          type: 'ARTICLE',
          target: '_blank',
        },
        {
          id: 'footer-item-4-6',
          title: 'Item 4.6',
          tags: ['tag23', 'tag24'],
          to: '/',
          type: 'ARTICLE',
          target: '_blank',
        },
      ],
    },
  ],
};
